### ISSUE TITLE
Research API's

### ISSUE THREAD

**Issue by dcoollx** [thinkful-ei-emu/RAMbo-Tracker-Server#5]
- [ ] API is mature

- [ ] API is well documented

- [ ] provides all necessary data

**Comment by hankyutae** [comment]
https://ndb.nal.usda.gov/ndb/doc/index
https://ndb.nal.usda.gov/ndb/doc/apilist/API-SEARCH.md
https://ndb.nal.usda.gov/ndb/doc/apilist/API-SEARCH.md
